services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/venv # Prevent overwriting container venv with local one
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Mapping to 5173 for local familiarity
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
